### ISSUE TITLE
GPU requirement

### ISSUE THREAD

**Issue by sauradip** [GuangxingHan/FCT#1]
Hi ,

Thanks for open-sourcing the code. WHat is the GPU requirement and what GPU RAM is necessary to run this code ? Can it be run on a single 2080 GPU for COCO ?

**Comment by GuangxingHan** [comment]
Thanks for your interest in our work.
It requires relatively large gpu ram (~50GB per gpu and 4gpus) for training with the pvt_v2_b2_li architecture.
We recommend using 4 A100 gpus for training. 

If you do not have that gpu resources, you can do the following,
- using our [pre-trained models](https://github.com/GuangxingHan/FCT#model-zoo).
- using smaller model, e.g., pvt_v2_b0.
