### ISSUE TITLE
How to generate final_split_voc_1_shot_instances_train2014.json?

### ISSUE THREAD

**Issue by zshanggu** [GuangxingHan/FCT#10]
Hi, Dr.Han. I was trying to generate the data splits for COCO. I followed the instructions in your Readme, and run the scripts under path "/datasets/coco", but I met some issue: 

1. I successfully run "python 1_split_filter.py ./" and correctly generate the "new_annotations/final_split_non_voc_instances_train2014.json".
2. I successfully run "python 2_gen_support_pool.py ./" and obtained the "train_support_df.pkl".
3. However, when I run "python 3_gen_support_pool_andy_shot_novel_class.py ./", it reported "FileNotFoundError: [Errno 2] No such file or directory: './new_annotations/final_split_voc_1_shot_instances_train2014.json'.

I checked the code in the previous 2 steps and didn't find any clue about this json file, could you help check if I missed somethings while runing "3_gen_support_pool_andy_shot_novel_class.py"?

**Comment by GuangxingHan** [comment]
Thanks for your interest in our work. 

Please run the script [3_novel_class_coco.py](https://github.com/GuangxingHan/FCT/blob/main/datasets/coco/3_novel_class_coco.py) before running 3_gen_support_pool_andy_shot_novel_class.py. Thanks.

**Comment by zshanggu** [comment]
Thanks, that works.
