### ISSUE TITLE
How to generate the 5000-image testing set for COCO?

### ISSUE THREAD

**Issue by greyhatjzy** [GuangxingHan/FCT#17]
I run python files in FCT-main\datasets\coco to prepare COCO. But the testing phase always took 40000+ images for evaluation.
I found this in [https://github.com/ucbdrive/few-shot-object-detection/blob/master/fsdet/data/builtin.py#L96](url), but I didn't find similar settings for COCO in FCT.
Is there any similar setting in FCT, or how can I correctly generate testing set for COCO?
Thanks a lot. (QWQ)

**Comment by GuangxingHan** [comment]
Actually, we did the exact same as the project https://github.com/ucbdrive/few-shot-object-detection/ for evaluation.

That's to say, please do the same process as https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/README.md#coco to use 5k.json for testing. The folder https://github.com/GuangxingHan/FCT/tree/main/datasets/coco is used to generate support images for meta-learning.  Hope this is helpful to you.

**Comment by greyhatjzy** [comment]
So the folder datasets/coco isn't used for testing. In testing phase, I only need to add a sentence like "coco_2014_test: (xxx/val2014, xxx/5k.json)" to config and use the "coco_2014_test" dataset to evaluate, as described in FSOD (it seemed to work). I wonder if I fully understand what you mean by doing this.

**Comment by GuangxingHan** [comment]
The folder datasets/coco can be used for both training/testing as long as you put appropriate files in it. We only show in this repository how to generate support images for meta-learning with these [scripts](https://github.com/GuangxingHan/FCT/tree/main/datasets/coco). Putting trainvalno5k.json, 5k.json and few-shot datasets under the folder is omitted here, but is required to train/evaluate our models, as we explained [here](https://github.com/GuangxingHan/FCT/tree/main#data-preparation).
